name: Sync Daily Solar Plot

on:
  schedule:
    # Runs daily at 04:30 UTC (12:30 PM Australia/Perth time)
    - cron: '35 4 * * *'
  workflow_dispatch: # Allows you to manually trigger this anytime from the Actions tab

jobs:
  sync-plot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-with: '3.10'

    - name: Install Databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

    - name: Download Figure from Databricks Workspace
      env:
        DATABRICKS_HOST: https://dbc-${{ vars.WORKSPACE_URL }}.cloud.databricks.com
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        # Use the GitHub variable to reconstruct the full path dynamically
        databricks workspace export \
          "${{ vars.DATABRICKS_DIR }}/solar-yield-forecasting-pipeline/7_Day_GTI_Power_Yield_Profile.png" \
          ./7_Day_GTI_Power_Yield_Profile.png \
          --object-type FILE \ --overwrite

    - name: Commit and Push Figure
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Only commit and push if the file actually changed/exists
        if [ -f daily_solar_yield.png ]; then
          git add daily_solar_yield.png
          git diff-index --quiet HEAD || git commit -m "chore: update daily solar yield plot [skip ci]"
          git push
        else
          echo "Figure file not found. Check Databricks path."
          exit 1
        fi
